version: "3"
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
volumes:
# auto create a new volume in docker. See docker context. the name of the volume = folder + volume name
  redis-data:
